ddweb/apps/images/urls.py
from django.conf.urls import url

from ddweb.apps.images.views import upload, upload_delete, uploadForm

urlpatterns = [
    url(r"^upload/", upload, name="jfu_upload"),
    url(r"^delete/(?P<pk>\d+)$", upload_delete, name="jfu_delete"),
    url(
        r"^uploadf/(?P<content_type>\w+)/(?P<object_id>\w+)",
        uploadForm,
        name="uploadform",
    ),
]

ddweb/apps/news/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [url(r"^$", TemplateView.as_view(template_name="news.html"), name="news")]

ddweb/apps/references/urls.py
from django.conf.urls import url

from ddweb.apps.references.views import references

urlpatterns = [url(r"^$", references, name="references")]

ddweb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
import django.views.static

admin.autodiscover()

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="company.html"), name="company"),
    url(r"^news/", include("ddweb.apps.news.urls"), name="news"),
    url(
        r"^contact/", TemplateView.as_view(template_name="contact.html"), name="contact"
    ),
    url(r"^references/", include("ddweb.apps.references.urls"), name="references"),
    url(r"^images/", include("ddweb.apps.images.urls"), name="images"),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r"^admin/", include(admin.site.urls)),
    # Temporary media (user uploaded static files) serving from dev server
    url(
        r"^media/(?P<path>.*)$",
        django.views.static.serve,
        {"document_root": settings.MEDIA_ROOT},
    ),
]

ddweb_app/urls.py
from django.conf.urls import patterns, url

from ddweb_app import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index')
)

ddweb/apps/images/models.py
import os
from django.contrib.contenttypes import fields
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.text import slugify


def file_name(instance, filename):
    sepFilename = os.path.splitext(filename)
    newFilename = slugify(sepFilename[0]) + sepFilename[1]
    content_type_folder = slugify(instance.content_type.model)
    object_id_folder = slugify(instance.object_id)
    return "/".join([content_type_folder, object_id_folder, newFilename])


class Image(models.Model):
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    associatedObject = fields.GenericForeignKey("content_type", "object_id")

    image = models.ImageField(upload_to=file_name)
    caption = models.CharField(max_length=200, blank=True)

ddweb/apps/references/models.py
from django.contrib.contenttypes import fields
from django.db import models

from ddweb.apps.images.models import Image


class Reference(models.Model):
    ship = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    constructionType = models.CharField(
        max_length=1,
        choices=(("n", "New Building"), ("r", "Refurbishment")),
        default="r",
    )
    year = models.PositiveIntegerField(blank=True, null=True)
    description = models.TextField(blank=True)
    ongoing = models.BooleanField(default=True)
    beforeDD = models.BooleanField(default=False)

    images = fields.GenericRelation(Image)

    class Meta:
        ordering = ["-year", "-id"]

    def __unicode__(self):
        if self.year:
            return self.ship + " " + str(self.year)
        else:
            return self.ship

ddweb/apps/images/views.py
import os
from django.contrib.auth.decorators import permission_required
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.decorators.http import require_POST
from jfu.http import upload_receive, UploadResponse, JFUResponse

from ddweb.apps.images.models import Image


@permission_required("image.add_image")
def uploadForm(request, content_type, object_id):
    ct = ContentType.objects.get(model=content_type)
    associatedObject = ct.get_object_for_this_type(pk=object_id)
    context = {
        "associatedObject": associatedObject,
        "content_type": content_type,
        "object_id": object_id,
    }
    return render(request, "upload.html", context)


@require_POST
@permission_required("image.add_image", raise_exception=True)
def upload(request):
    # The assumption here is that jQuery File Upload
    # has been configured to send files one at a time.
    # If multiple files can be uploaded simulatenously,
    # 'file' may be a list of files.
    image = upload_receive(request)
    content_type = ContentType.objects.get(model=request.POST["content_type"])
    object_id = request.POST["object_id"]
    instance = Image(image=image, content_type=content_type, object_id=object_id)
    instance.save()

    basename = os.path.basename(instance.image.path)

    file_dict = {
        "name": basename,
        "size": image.size,
        "url": instance.image.url,
        "deleteUrl": reverse("jfu_delete", kwargs={"pk": instance.pk}),
        "deleteType": "POST",
    }

    return UploadResponse(request, file_dict)


@require_POST
@permission_required("image.delete_image", raise_exception=True)
def upload_delete(request, pk):
    success = True
    try:
        instance = Image.objects.get(pk=pk)
        os.unlink(instance.image.path)
        instance.delete()
    except Image.DoesNotExist:
        success = False

    return JFUResponse(request, success)

ddweb/apps/references/views.py
from django.shortcuts import render

from ddweb.apps.references.models import Reference


def references(request):
    ongoing = Reference.objects.filter(ongoing=True)
    finished = Reference.objects.filter(ongoing=False, beforeDD=False)
    before = Reference.objects.filter(beforeDD=True)
    context = {"references": [ongoing, finished], "before": before}
    return render(request, "references.html", context)

ddweb_app/views.py
from django.http import HttpResponse
from ddweb_app.models import Reference

def index(request):
    rList = Reference.objects.all()
    output = rList
    return HttpResponse(output)

ddweb/apps/images/templates/upload-form.html
{% extends 'jfu/upload_form.html' %}

{% block JS_INIT %}

        $('#fileupload').fileupload({

            formData: [
                { name: "csrfmiddlewaretoken", value: "{{ csrf_token }}" },
                { name: "content_type", value: "{{ content_type }}" },
                { name: "object_id", value: "{{ object_id }}" },
            ],

            {% block JS_OPTS %}
              autoUpload: true,
              sequentialUploads: true,
            {% endblock %}

        });
{% endblock JS_INIT %}

ddweb/apps/images/templates/upload.html
<!DOCTYPE html>
<html{% if request.LANGUAGE_CODE %} lang="{{ request.LANGUAGE_CODE }}"{% endif %}>
  <head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}style.min.css" />
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="{{ STATIC_URL }}logo.svg" alt="Danish Decoration" id="logo-image" /> </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'company' %}">Company</a></li>
            <li><a href="{% url 'news' %}">News</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
            <li><a href="{% url 'references' %}">References</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" role="main">
      <div class="page-header">
        <h1>{% block title %}News{% endblock %}</h1>
      </div>
      <h2>Tilføj billeder til: {{ associatedObject }}</h2>
      {% load jfutags %}
      {% jfu 'upload-form.html' %}
    </div>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container navbar-text text-center">
        <p>
          &copy;2008-2015 <a href="/">Danish Decoration Ship Interior Consulting ApS.</a> All rights reserved. &middot; <a href="mailto:webmaster@danishdecoration.dk">Contact webmaster</a>
        </p>
      </div>
    </nav>
    <script type="text/javascript" src="{{ STATIC_URL }}yoxview/yoxview-init.js"></script>
    {% block js %}{% endblock js%}
  </body>
</html>

ddweb/apps/news/templates/news.html
{% extends 'base.html' %}
{% load instagram_client news %}

{% block title %}News{% endblock title %}

{% block content %}
{% instagram_user_recent_media Danish_Decoration %}
{% for media in recent_media %}
    <div class="row">
        <div class="col-xs-12">
            <div class="thumbnail">
                <a href="//instagram.com/p/{{ media.shortcode }}" target="_blank">
                    <img src="{{ media.thumbnail_src }}"
                         class="img-responsive center-block img-thumbnail"
                         alt="{{ media.edge_media_to_caption.edges.0.node.text }}" />
                </a>
                <div class="caption center-block" style="max-width: 640px">
                    <p class="lead">{{ media.edge_media_to_caption.edges.0.node.text }}</p>
                    <p><time datetime="{{ media.taken_at_timestamp|fromtimestamp|date:"c" }}" title="{{ media.taken_at_timestamp|fromtimestamp|date:"c" }}">{{ media.taken_at_timestamp|fromtimestamp|timesince }}</time> ago.</p>
                </div>
            </div>
        </div>
    </div>
<hr/>
{% endfor %}
{% endblock content%}

ddweb/apps/references/templates/references.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}References{% endblock title%}

{% block content %}
<p>
  The company, founded in 2008, is comparatively young, but the people
  have more than 25 years of experience within the industry. We have
  worked on prominent project before and after the founding of this
  company.
</p>

{% for list in references %}
<div class="page-header">
    <h2>{% cycle "Ongoing Projects" "References" %}</h2>
</div>
{% for project in list %}
<div class="row">
  <div class="col-sm-9">
    <div class="row">
      <div class="col-xs-9 col-sm-6">
        <h4>{{ project.ship }}</h4>
      </div>
      <div class="col-xs-3 col-sm-2 col-sm-push-4 text-right">
        <h4>{{ project.year }}</h4>
      </div>
      <div class="col-xs-12 col-sm-4 col-sm-pull-2">
        <h5>{{ project.owner }}</h5>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-6">
        <p class="small">{{ project.place }}</p>
      </div>
      <div class="col-xs-6 text-right">
        <p class="small">{{ project.get_constructionType_display }}</p>
      </div>
    </div>
    <p>{{ project.description }}</p>
  </div>
  <div class="col-xs-12 col-sm-3 vertical-align">
      {% if project.images.all %}
      <div class="carousel slide">
          <div class="carousel-inner">
              {% for Image in project.images.all %}
              {% thumbnail Image.image '720x720' as sm %}
              {% if forloop.counter <= 3 %}
              <div class="item{% if forloop.first %} active{% endif %}">
                  <a href="{{ sm.url }}"
                     data-toggle="lightbox"
                     data-gallery="{{ project.headline|slugify }}-{{ project.date|slugify }}"
                     data-title="{{ Image.image.caption }}">
                      {% thumbnail Image.image '262x262' crop='center' as xs %}
                      <img src="{{ xs.url }}"
                           class="img-responsive center-block img-thumbnail"
                           alt="{{ Image.image.caption }}" />
                      {% endthumbnail %}
                  </a>
              </div>
              {% else %}
              <div data-remote="{{ sm.url }}"
                   data-toggle="lightbox"
                   data-gallery="{{ project.headline|slugify }}-{{ project.date|slugify }}"
                   data-title="{{ Image.image.caption }}"></div>
              {% endif %}
              {% endthumbnail %}
              {% endfor %}
          </div>
      </div>
      {% else %}
      <p class="hidden-xs text-center small">No images</p>
      {% endif %}
  </div>
</div>
<hr />
{% endfor %}
{% endfor %}

<div class="page-header">
  <h2>Personal References</h2>
</div>
<p>Personal references from before the founding of Danish Decoration.</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Ship</th>
      <th>Owner</th>
      <th>Year</th>
    </tr>
  </thead>
  <tbody>
    {% for project in before %}
    <tr> <td>{{ project.ship }}</td><td>{{ project.owner }}</td><td>{{ project.year }}</td> </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock content%}

templates/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html{% if request.LANGUAGE_CODE %} lang="{{ request.LANGUAGE_CODE }}"{% endif %}>
  <head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    <link type="text/css" rel="stylesheet" href="{% bootstrap_css_url %}" />
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}ekko-lightbox/dist/ekko-lightbox.min.css" />
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="{{ STATIC_URL }}logo.svg" alt="Danish Decoration" id="logo-image" /> </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'company' %}">Company</a></li>
            <li><a href="{% url 'news' %}">News</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
            <li><a href="{% url 'references' %}">References</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" role="main">
      <div class="page-header">
        <h1>{% block title %}{% endblock %}</h1>
      </div>
      {% block content %}(no content){% endblock %}
    </div>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-text text-center">
          <p>
            &copy;2008-2023 <a href="/">Danish Decoration Ship Interior Consulting ApS.</a> All rights reserved. &middot; <a href="mailto:webmaster@danishdecoration.dk">Contact webmaster</a>
          </p>
        </div>
      </div>
    </nav>

    {% bootstrap_javascript jquery=1 %}
    <script type="text/javascript" src="{{ STATIC_URL }}ekko-lightbox/dist/ekko-lightbox.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function ($) {
        $(document).delegate('*[data-toggle="lightbox"]', 'click', function(event) {
          event.preventDefault();
          $(this).ekkoLightbox();
        });
      });
     $('.carousel').carousel();
    </script>
    {% block js %}{% endblock js%}
  </body>
</html>

templates/company.html
{% extends 'base.html' %}

{% block title %}Company{% endblock title %}

{% block content %}
<div class="row">
  <div class="col-sm-12">
    <div class="col-xs-12 col-sm-8 pull-right">
      <img class="img-responsive" alt="Danish Decoration - Connection to success."  src="{{ STATIC_URL }}dd2s.jpg" />
    </div>
    <p>We started our own company when the management of Danish Interior
      A/S, decided to cease operations in Denmark. Danish Decoration, Ship
      Interior Consulting ApS, referred to as “Danish Decoration” was
      established on July 4th, 2008. All the principals have been working
      with various companies in the cruise business for twenty years or
      more. We have all worked in various positions as Project Manager,
      On-Site Manager and Assistant Project Manager. This is also the reason
      for the way we have built our Reference List. As Danish Decoration is
      a young company it may look a little odd with this many references. We
      have simply listed the major part of the various projects where we
      personally have held a position. Danish Decoration has begun well by
      signing long term contracts with R&amp;M Ship Tec Group. Our goal is
      to establish new partners while continuing the existing relations we
      have developed. We offer Project Management services related to
      interior refurbishment in public areas on cruise ships and ferries.
      We also specialize in consulting and procurement services.  We have
      great experience both on new buildings and on Refits, and we offer
      both.</p>
  </div> <!-- col-sm-12 -->
</div> <!-- row -->


{% endblock content%}

templates/contact.html
{% extends 'base.html' %}

{% block js%}{% endblock %}

{% block title %}Contact{% endblock title %}

{% block content %}
<div class="col-sm-4">
  <address>
    Danish Decoration<br />
    Garvergade 4<br />
    DK-9400 Nørresundby<br />
    Denmark<br />
    E-mail: <a href="mailto:info@danishdecoration.dk">info@danishdecoration.dk</a>
  </address>

  <address>
    <strong>Tina Kjeldgaard</strong><br />
    Project Manager<br />
    Mobile: +45 30 68 09 76<br />
    E-mail: <a href="mailto:tik@danishdecoration.dk">tik@danishdecoration.dk</a><br />
  </address>

  <address>
    <strong>Claus B. Hansen</strong><br />
    Project Manager<br />
    Mobile: +45 30 68 09 75<br />
    E-mail: <a href="mailto:cbh@danishdecoration.dk">cbh@danishdecoration.dk</a><br />
  </address>

  <address>
    <strong>Mathias Dannesbo</strong><br />
    Assistant & IT<br />
    E-mail: <a href="mailto:md@danishdecoration.dk">md@danishdecoration.dk</a><br />
  </address>
</div>
<div class="col-sm-8">
  <img class="img-responsive" alt="Danish Decoration - Connection to success."  src="{{ STATIC_URL }}dd2s.jpg" />
</div>
{% endblock content%}